// First bundled stage — a classic indoor-dojo kung-fu battlefield, sliced from a
// MUGEN reference. Two background layers: the mountain panorama is the FAR layer
// (seen through the wall's window + top slats; parallax-drifts as the camera
// pans), the dojo wall is the NEAR layer at the fighting plane (its window/slats
// are cut to transparent). Later stages can be generated by Nano Banana 2 to the
// same 960×460 layer / 960×80 floor layout and swapped in by pointing StageArt at
// the generated URLs.
import type { StageArt } from '../../render/background.ts';
import sceneryUrl from './scenery.png';
import wallUrl from './wall.png';
import floorUrl from './floor.png';

export const hillsideStage: StageArt = {
  id: 'hillside',
  name: 'Hillside Dojo',
  layers: [
    { url: sceneryUrl, parallax: 0.35 }, // mountains beyond the window — far, drifts slow
    { url: wallUrl, parallax: 1 }, // dojo back wall — fighting plane, openings show scenery
  ],
  floorUrl,
  // Floor's far edge sits above the feet line (460) so the wooden platform
  // recedes behind the fighters — they stand mid-floor, not on its back edge.
  groundY: 400,
  backColor: 0x8a6a3f, // wood tone — backs any edge seam so it never flashes the app bg
};
